# -*- coding: utf-8 -*-
"""connect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWYkG1cdtUvOQHIK6ZVSVeox-BxQwDZg
"""

# connect.py
import os

# point to the DB
DATAPATH = os.environ.get("RESEARCH_DATA_PATH")