# -*- coding: utf-8 -*-
"""downstream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vX5vx7smuVwrusvmsJwzce9JAtXxMZfo
"""

# downstream.py

import pandas as pd
from connect import DATAPATH

def get_fred_data(subset, start_dt="2001-01-01", end_dt="2005-12-31"):
  """Get FRED data from the DB."""
  
  filename = DATAPATH + "fred_data.ftr"

  data = pd.read_ftr(filename)

  return data